blog/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #Home
  root 'articles#index'

  #About
  get 'about', to: 'pages#about'

  #Articles
  resources :articles

  #drafts
  get '/drafts', to: 'articles#drafts'

  #Tags
  get '/tags', to: 'tags#index'
  post '/tags', to: 'tags#create'
  get '/tags/new', to: 'tags#new'
  get 'tags/:id/edit', to: 'tags#edit'
  get '/tags/:taggy', to: 'articles#index', as: 'tag', param: :taggy
  patch 'tags/:id', to: 'tags#update'
  put 'tags/:id', to: 'tags#update'
  delete 'tags/:id', to: 'tags#destroy'





  post 'publish_draft', to: 'articles#publish_draft'

  #En vez de usar resources, también puede ser:
  #get '/articles', to 'articles#index'
  #get '/articles/:id', to 'articles#show', as 'article'
  #y así...

  devise_for :users, controllers: { registrations: "registrations"}

  #ckeditor stuff
  mount Ckeditor::Engine => '/ckeditor'

end

blog/app/models/tag.rb
class Tag < ApplicationRecord
  validates_presence_of :taggy
  validates_uniqueness_of :taggy

  validates :taggy, format: { without: /\s/ }

  has_and_belongs_to_many :articles

end

blog/app/controllers/tags_controller.rb
class TagsController < ApplicationController

  before_action :get_tag_by_id, only: [:edit, :update, :show, :destroy]
  before_action :require_admin, only: [:new, :edit, :update, :destroy]


  def new
    @tag = Tag.new
  end


  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      #Notificamos éxito
      flash[:notice] = "tag successfully created"
      redirect_to tag_path(@tag)
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @tag.update(tag_params)
      flash[:notice] = "tag Successfully updated"
      redirect_to tag_path(@tag)
    else
      render :edit
    end
  end

  def index

    @tags = Tag.all
    @tags = @tags.paginate(:page =>params[:page]).order('created_at DESC')


    #Can be fetched with html or js
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
  end

  def destroy
    if @tag.destroy
      flash[:notice] = "tag successfully deleted"
      redirect_to tags_path
    end

  end

  private

  def get_tag_by_id
    @tag = Tag.find(params[:id])
  end

  def tag_params
    params.require(:tag).permit(:taggy)
  end

end

blog/app/views/tags/_form.erb
<%= form_for @tag do |f| %>

    <%= f.label :taggy %><br>
    <%= f.text_field :taggy %>

    <%= f.submit %>
<% end %>

blog/app/views/tags/_tag.html.erb
<div>
  <h2><%= link_to tag.taggy, tag_path(tag) %></h2>
</div>

blog/app/views/tags/edit.html.erb
<h1>Edit article</h1>
<%=render 'form'%>

blog/app/views/tags/index.html.erb
<div id="my-posts">
  <%= render @tags %>
</div>

<div id="infinite-scrolling">
  <%= will_paginate %>
</div>

<% if @tags.next_page %>
    <div id="load_more_posts">More posts</div>
<% end %>

blog/app/views/tags/index.js.erb
$('#my-posts').append('<%= j render @tags %>');
<% if @tags.next_page %>
    $('.pagination').replaceWith('<%= j will_paginate @tags %>');
    $('.pagination').hide();
<% else %>
    $('.pagination, #load_more_posts').remove();
<% end %>

blog/app/views/tags/new.html.erb
<h1>Create a tag</h1>
<%=render 'form'%>

blog/app/views/tags/show.html.erb
<div class="col-sm-11 col-xs-12 blog-content">
  <h2 class="text-center"><%= @tag.taggy %></h2>
  <h5 class="text-center"><%= @tag.created_at %></h5>
</div>


<p><%= link_to "Edit", edit_tag_path(@tag)%></p>
<p><%= link_to "Return to list", tags_path%></p>