blog/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #Home
  root 'articles#index'

  #About
  get 'about', to: 'pages#about'

  #Articles
  resources :articles

  #drafts
  get '/drafts', to: 'articles#drafts'

  #Tags
  get '/tags', to: 'tags#index'
  post '/tags', to: 'tags#create'
  get '/tags/new', to: 'tags#new'
  get 'tags/:id/edit', to: 'tags#edit'
  get '/tags/:taggy', to: 'articles#index', as: 'tag', param: :taggy
  patch 'tags/:id', to: 'tags#update'
  put 'tags/:id', to: 'tags#update'
  delete 'tags/:id', to: 'tags#destroy'





  post 'publish_draft', to: 'articles#publish_draft'

  #En vez de usar resources, también puede ser:
  #get '/articles', to 'articles#index'
  #get '/articles/:id', to 'articles#show', as 'article'
  #y así...

  devise_for :users, controllers: { registrations: "registrations"}

  #ckeditor stuff
  mount Ckeditor::Engine => '/ckeditor'

end

blog/app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: {minimum: 3, maximum: 140}
  validates :content, presence: true
  validates :user_id, presence: true

  belongs_to :user
  has_and_belongs_to_many :tags

  #Header image
  has_attached_file :header_img, styles: {large: "1500x1500>", medium: "600x600>", thumb: "150x150#"}, default_url: 'https://s3.eu-west-2.amazonaws.com/luismoyanoblog/articles/header_imgs/medium/missing.png'
  validates_attachment_content_type :header_img, content_type: /\Aimage\/.*\Z/


  TAGS_PREVIEW_LIMIT = 2.freeze

  def timestamp
    created_at.strftime('%d %B %Y %H:%M:%S')
  end

  def short_timestamp
    created_at.strftime('%m/%Y')
  end

end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

before_action :get_article_by_id, only: [:edit, :update, :show, :destroy, :publish_draft]
before_action :require_same_user, only: [:edit, :update, :destroy]
before_action :require_user, only: [:new]
  def new
    @article = Article.new
  end


  def create
    @article = Article.new(article_params)
    @article.user = current_user

    #Guardo los tags
    params[:article][:tags].each{ |tag_id|
      if tag_id != ""
        @tag = Tag.find_by_id(tag_id.to_i)
        @article.tags << @tag
      end
    }

    if @article.save
      #Notificamos éxito
      flash[:notice] = "Article successfully created"
      redirect_to article_path(@article)
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article Successfully updated"
      redirect_to article_path(@article)
    else
      render :edit
    end
  end

def index
  if !params[:taggy].blank?
    get_articles_by_tag(params[:taggy])
  else
    get_all_articles
  end

end

def drafts
  get_all_drafts
  render :index
end

def publish_draft

  if @article.draft?
    @article.draft = false;
    @article.save!
  end

  redirect_to article_path(@article)

end

def show
end


def destroy
  if @article.destroy
      flash[:notice] = "Article successfully deleted"
      redirect_to articles_path
    end
  end

  private

  def get_article_by_id
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content, :draft, :header_img)
  end

  def require_same_user
    if current_user.blank? || @article.user != current_user
      flash[:danger] = "You can only modify your own stuff"
      redirect_to root_path
    end
  end

  def require_user
    if current_user.blank?
      flash[:danger] = "You can only modify your own stuff"
      redirect_to root_path
    end
  end

  def paginate_articles
    if !@articles.blank?
      @articles = @articles.paginate(:page =>params[:page]).order('created_at DESC')
    end

  end

  def fetch_html_js
    #Can be fetched with html or js
    respond_to do |format|
      format.html
      format.js
    end
  end

  def get_all_articles
    @articles = Article.where(draft: false)

    paginate_articles
    fetch_html_js
  end

  def get_articles_by_tag(tag)
    @tag = Tag.find_by_taggy(tag)
    if(!@tag.blank?)
      @articles = @tag.articles.where(draft: false)
    end

    paginate_articles
    fetch_html_js
  end

  def get_all_drafts
    @articles = Article.where(draft: true)

    paginate_articles
    fetch_html_js
  end

end

blog/app/views/articles/_article.html.erb
<div class='article-preview'>
  <ul class= 'article-preview-tags'>
      <% article.tags.first(Article::TAGS_PREVIEW_LIMIT).each do |tag| %>
        <li class='article-tag'> <%= link_to tag.taggy, tag_path(tag.taggy) %> </li>
      <% end %>
      <% if ((@more_tags = article.tags.count - Article::TAGS_PREVIEW_LIMIT) > 0) %>
        <li class='article-tag'> <%= '+' + @more_tags.to_s + '...'%> </li>
      <% end %>
  </ul>
  <%= link_to article_path(article) do %>
    <div class='article-flex'>

      <%= image_tag article.header_img.url(:medium), class: 'article-preview-img' %>

      <h2 class= 'article-preview-title'><%= article.title %></h2>

      <p class='article-preview-sub'><%= truncate(strip_tags(article.content), length: 200) %></p>

      <!--<small><em class="article-time"><%= article.timestamp %></em></small>-->

      <% if article.draft? %>
        <em class= 'article-preview-draft'> This article is a draft </em>
      <% end %>
    </div>
  <% end %>
</div>

blog/app/views/articles/_article_list.html.erb
<% if !@articles.blank? %>
  <div id="my-posts" class='articles-list'>
    <%= render @articles %>
  </div>

  <div id="infinite-scrolling">
    <%= will_paginate %>
  </div>

  <% if @articles.next_page %>
      <div id="load_more_posts" class='load-more-button'>More posts</div>
  <% end %>
<% end %>

blog/app/views/articles/_form.erb
<div class= 'article-form-container'>
  <%= form_for @article, html: { multipart: true } do |f| %>

      <%= f.label :header_img, class: 'editor-label' %>
      <%= f.file_field :header_img, class: 'editor-header-input'%><br>

      <%= f.text_field :title, class: 'editor-article-title', placeholder: 'Title' %>

      <%= f.label :content %><br>
      <%= f.cktext_area :content, :ckeditor => {:toolbar => 'FULL'}, class: 'articles-editor' %>

      <%= f.select :tags, Tag.all.collect{|tag| [tag.taggy, tag.id]}, {}, multiple: true, class: 'editor-tags-selector' %>

      <div class="check-draft">
        <%= f.check_box :draft %>
        <%= f.label "Save as Draft", class: 'draft-label' %><br>
      </div>
      <%= f.submit 'Publish article', class:'session-button' %>
  <% end %>
</div>

blog/app/views/articles/edit.html.erb
<h2 class='edit-article-title'>Edit article</h2>
<%=render 'form'%>

blog/app/views/articles/index.html.erb
<%= render partial: 'article_list' %>

blog/app/views/articles/index.js.erb
$('#my-posts').append('<%= j render @articles %>');
<% if @articles.next_page %>
    $('.pagination').replaceWith('<%= j will_paginate @articles %>');
    $('.pagination').hide();
<% else %>
    $('.pagination, #load_more_posts').remove();
<% end %>

blog/app/views/articles/new.html.erb
<h2 class='edit-article-title'>Create an article</h2>
<%=render 'form'%>

blog/app/views/articles/show.html.erb
<div class="article-content">

  <div class="article-header-zone" style="background-image: url(<%=@article.header_img.url(:large)%>);">
    <div class='article-title-container'>
      <h2 class="article-title"><%= @article.title %></h2>
    </div>
  </div>

  <div class='article-content-zone'><%= raw @article.content %></div>

  <h5 class="article-time"><%= @article.short_timestamp %></h5>

  <ul>
    <% @article.tags.each do |tag| %>
      <li class='article-tag'> <%= link_to tag.taggy, tag_path(tag.taggy) %> </li>
    <% end %>
  </ul>


  <% if @article.draft? %>
    <em class='draft-tag'> This article is a draft </em>
    <%= button_to "Publish", action: :publish_draft, :articleid => @article.id %>
  <% end %>

</div>

<div class='article-end-list'>
  <% if !current_user.blank? %>
    <p><%= link_to "Edit", edit_article_path(@article)%></p>
  <% end %>

  <p><%= link_to "Return to list", articles_path%></p>
</div>