blog/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #Home
  root 'articles#index'

  #About
  get 'about', to: 'pages#about'

  #Articles
  resources :articles

  #drafts
  get '/drafts', to: 'articles#drafts'

  #Tags
  get '/tags', to: 'tags#index'
  post '/tags', to: 'tags#create'
  get '/tags/new', to: 'tags#new'
  get 'tags/:id/edit', to: 'tags#edit'
  get '/tags/:taggy', to: 'articles#index', as: 'tag', param: :taggy
  patch 'tags/:id', to: 'tags#update'
  put 'tags/:id', to: 'tags#update'
  delete 'tags/:id', to: 'tags#destroy'





  post 'publish_draft', to: 'articles#publish_draft'

  #En vez de usar resources, también puede ser:
  #get '/articles', to 'articles#index'
  #get '/articles/:id', to 'articles#show', as 'article'
  #y así...

  devise_for :users, controllers: { registrations: "registrations"}

  #ckeditor stuff
  mount Ckeditor::Engine => '/ckeditor'

end

blog/app/views/layouts/_article_thumb.html.erb
<% if !@article.blank? %>
  <div class="article-home-thumb">
    <a href="/">
      <img alt='logo' class='logo-thumb' src='https://s3.eu-west-2.amazonaws.com/luismoyanoblog/logo/Logo_color.png?versionId=M5SBYqTepT5kW16cOzd8FgGJAgRqF.JE'>
    </a>
  </div>
<% end %>

blog/app/views/layouts/_blog_view.html.erb
<% if !ActiveModel::Type::Boolean.new.cast(ENV['MANTEINANCE_MODE']) %>
  <%= render 'layouts/menu_layout' %>
  <%= render 'layouts/header' %>
  <%= render 'layouts/devise_msg' %>
  <%= render 'layouts/article_thumb' %>
<% end %>

blog/app/views/layouts/_devise_msg.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

blog/app/views/layouts/_header.html.erb
<div class= "<%="#{'article-display' if !@article.blank?}" %>">
  <div class= 'header'>
    <%= link_to root_path, class: 'header-home' do %>
      <div class='header-left'>

          <img alt='logo' class='header-logo' src='https://s3.eu-west-2.amazonaws.com/luismoyanoblog/logo/Logo_color.png?versionId=M5SBYqTepT5kW16cOzd8FgGJAgRqF.JE' >
          <h1>Luis Moyano</h1>

      </div>
      <%= render partial:'layouts/menu_links', locals:{html_class: "menu-header-item"} %>
    <% end %>

    <div class='header-right'>
      <% if !current_user.blank? %>
        <p class='author-header'><%= current_user.author %></p>
      <% end %>
      <%= ion_icon 'android-menu', onclick:"openMenu()" %>
    </div>
  </div>
</div>

blog/app/views/layouts/_menu_layout.html.erb
<div class="menu-layout" id='menu-overlay'>
  <%= ion_icon 'close', class: 'menu-layout-close', onclick:'closeMenu()'%>

  <%= render partial:'layouts/menu_links', locals:{html_class: "menu-layout-item"} %>

  <%= render partial:'layouts/rrss', locals:{html_class: "layout-media-icons"} %>

</div>

blog/app/views/layouts/_menu_links.html.erb
<ul>
  <% if html_class != "menu-header-item" %>
    <li class="<%= html_class %>"><%= link_to 'Home', root_path %></li>
  <% end %>
  <li class="<%= html_class %>"><%= link_to 'About', about_path %></li>
  <% if !current_user.blank? %>
    <li class="<%= html_class %>"> <%= link_to 'New article', new_article_path %> </li>
    <li class="<%= html_class %>"> <%= link_to 'drafts', drafts_path %> </li>
    <li class="<%= html_class %>"> <%= link_to('Sign out', destroy_user_session_path, method: :delete) %> </li>
  <% end %>

</ul>

blog/app/views/layouts/_messages.erb
<ul>
  <% flash.each do|name, msg|%>
      <li><%=msg%></li>
  <%end%>
</ul>

blog/app/views/layouts/_rrss.html.erb
<div class= <%= html_class %> >
  <a href='https://www.facebook.com/luis.muleta'><%= ion_icon 'social-facebook-outline' %></a>
  <a href='https://www.instagram.com/lmoyanomedina/'><%= ion_icon 'social-instagram-outline' %></a>
  <a href='https://gitlab.com/luismoyano'><%= ion_icon 'network' %></a>
</div>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Luis's stuff</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'ckeditor/ckeditor.js' %>

    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Raleway" rel="stylesheet">

    <link rel="icon" type="image/png" href="https://s3.eu-west-2.amazonaws.com/luismoyanoblog/logo/favicon-32x32.png" sizes="32x32" />
    <link rel="icon" type="image/png" href="https://s3.eu-west-2.amazonaws.com/luismoyanoblog/logo/favicon-16x16.png" sizes="16x16" />


  </head>

  <body>
    <%= render 'layouts/blog_view' %>
    <%= yield %>
  </body>
</html>